apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1 # This rewrites the path to match the backend service
spec:
  ingressClassName: nginx # Specify the ingress class to use
  rules:
    - host: ticketing.dev
      http:
        paths:
          - path: /api/v1/user/?(.*)
            pathType: ImplementationSpecific # This allows regex paths
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
  
# spec:
#   rules:
#     - host: ticketing.dev
#       http:
#         paths:
#           - path: /api/v1/user/?(.*)
#             backend:
#               serviceName: auth-srv
#               servicePort: 3000
          
          # - path: /?(.*)
          #   backend:
          #     serviceName: client-srv
          #     servicePort: 3000
