import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { AuthProvider } from "@/app/context/auth-context";
import { Toaster } from "react-hot-toast";


const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Ticketing App",
    template: "%s | Ticketing App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased font-[family-name:var(--font-inter)`}
      >
        <div>
          <AuthProvider>
            <Header />
            <main className="container mx-auto mt-8 flex min-h-screen max-w-7xl justify-center">
              {children}
            </main>
          </AuthProvider>

          <Footer />
          <Toaster position='top-right' />
        </div>
      </body>

    </html>
  );
}
