name: Tests & Build auth MS

on:
  push:
    branches: [ "master" ]
    # paths:
    #   - 'apps/auth/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'apps/auth/**'

jobs:
  test:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
      - run: cd apps/auth && npm install && npm run test:ci 

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd apps/auth && docker build -t ahmedoun96/auth .
      - run: docker push ahmedoun96/auth
