name: Tests tickets

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths: apps/tickets

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x', '22.x']

    steps:
      - uses: actions/checkout@v4
      - name: Test tickets MS using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: cd apps/tickets
      - run: npm install
      - run: npm run test:ci
