name: Tests auth MS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths:
      - 'apps/auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
      
      - run: cd apps/tickets
      - run: npm install
      - run: npm run test:ci
