name: Tests tickets MS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths: apps/tickets/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 
      - run: cd apps/tickets && npm install && npm run test:ci